export enum TourType {
  ListPagesTour = 'ListPagesTour',
  UpsetChartTour = 'UpsetChartTour',
  CustomListTour = 'CustomListTour',
  FilterValueEnrichment = 'FilterValueEnrichment',
  Heatmaps = 'Heatmaps',
  StructureSearchTour = 'StructureSearchTour',
  TargetExpressionTour = 'TargetExpressionTour',
  WhatsNew318 = 'WhatsNew318',
  TINXNovelty = 'TINXNovelty',

  ShortSearch = 'ShortSearch',
  ShortTargetDetails = 'ShortTargetDetails',
  ShortValueCounts = 'ShortValueCounts',
  ShortHeatmap = 'ShortHeatmap',
  ShortSequenceSearch = 'ShortSequenceSearch',
  ShortCommonDoc = 'ShortCommonDoc',
  ShortPPIList = 'ShortPPIList',
  ShortDiseaseDetails = 'ShortDiseaseDetails',
  ShortExpressionAtlas = 'ShortExpressionAtlas',
  ShortDownload = 'ShortDownload',
  ShortLigandList = 'ShortLigandList',
  ShortCustomList = 'ShortCustomList',
  ShortPredictionResults = 'ShortPredictionResults'
}
